
[window]
padding.x = 10
padding.y = 10
#decorations = "Buttonless"
opacity = 0.8
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 17

[selection]
save_to_clipboard = true

[general]
import = [
    "~/.config/alacritty/themes/night_owl.toml"
]
